### ISSUE TITLE
Pack all images into one binary

### ISSUE THREAD

**Issue by pkmonster** [thstkdgus35/EDSR-PyTorch#109]
Hello, I would like to ask you about the situation where "pack all DIV2K images in one binary file" and use single binary files. 

The training speed would be different or not ? 

I am using 1080ti and use single binary files. It took 7s to finish 1600. I am wondering about the speed for packing all to one binary file. 

![screenshot from 2019-01-16 01-38-09](https://user-images.githubusercontent.com/16741872/51198530-70e93600-192f-11e9-884e-02e95deb24c9.png)

2/ We need to do pre-processing before ora fter convert images into binary files ? 

Thank you

**Comment by thstkdgus35** [comment]
Hello.

Actually, there is a bug in the time measuring. If we do not use ``torch.cuda.synchronize()`` after having some CUDA calls (like forward/backward), python cannot measure exact time because those CUDA calls are running in the background. However, if I include synchronization in the code, it gets slower (<0.5s per 100 batches). If you include synchronization after [this line](https://github.com/thstkdgus35/EDSR-PyTorch/blob/9a9d7d74a5a7e010e34bc9784f0e83d6055d85e7/src/trainer.py#L55), you will found that your system works well as you expected, even with separated binary files (ex. ``7.7s+0.3s``).

Thank you for reporting.
