### ISSUE TITLE
Question about the training and testing

### ISSUE THREAD

**Issue by wfz0755** [thstkdgus35/EDSR-PyTorch#112]
Hi @thstkdgus35 ,
May I ask why you use patches from pictures for the training but end up feeding the whole image into the EDSR during inference(instead of patches of the image)?
I am new to super-resolution and curious about that. 

Thanks!
Fangzhou

**Comment by thstkdgus35** [comment]
Sorry about the late response.

Of course, it is possible to feed whole images during training. However, due to some issues, we prefer patch-based learning.

1. Images may have different sizes so we cannot make an efficient batch with them.
2. In contrast to the classification problem which utilizes whole image region for inference, the receptive field of the SR model is often limited. Therefore, we do not have to feed entire images during training.
3. It requires huge memory!

Thank you.

**Comment by wfz0755** [comment]
Thank you so much!
