### ISSUE TITLE
Using Multiple GPUs

### ISSUE THREAD

**Issue by adamian98** [thstkdgus35/EDSR-PyTorch#12]
I successfully trained the x2 model from the paper using multiple GPUs thanks to the following code in code/models/\_\_init\_\_.py:

```
if self.args.n_GPUs > 1:
                my_model = nn.DataParallel(my_model, range(0, self.args.n_GPUs))
                print('\tMultiple GPUs Ready!')
```

However, I ran into problems when trying to use this model to train the x4 from the paper. This is because in the same file (\_\_init\_\_.py), when loading a model instead of creating one, the program attempts to load the model before enabling multiple GPUs. This is a problem since the keys of the saved x2 model all start with "module" while the keys from the empty dictionary do not. It therefore throws a KeyException.

I tried to fix this by switching the order of the GPU initialization and the dictionary loading, however it then complains about missing keys. Specifically, the error message is

> KeyError: 'missing keys in state_dict: "{\'module.tail.0.2.bias\', \'module.tail.0.2.weight\'}"'

Is there a better way to try and fix the problem? Thank you very much.

**Comment by thstkdgus35** [comment]
Hello.

Thank you for reporting the bug.

It happens because the PyTorch wraps a model with nn.DataParallel when using multiple GPUs.

The quickest solution is load the state after making DataParallel module.

You can do this by paste line 16~18 to below the line 25.

I will fix this bug as soon as possible.

Thank you.

Sanghyun.

**Comment by thstkdgus35** [comment]
Fixed!
