### ISSUE TITLE
pretrain model download

### ISSUE THREAD

**Issue by wm901115nwpu** [thstkdgus35/EDSR-PyTorch#120]
I can't download pretrain model

**Comment by thstkdgus35** [comment]
Would you please specify your configuration so that I can reproduce the issue and fix it?

**Comment by wm901115nwpu** [comment]
# pretrained model can be downloaded from https://www.dropbox.com/s/mjbcqkd4nwhr6nu/models_ECCV2018RCAN.zip?dl=0
 this url is not available

**Comment by thstkdgus35** [comment]
@wm901115nwpu Sorry, that model is not from us.

Please contact the original authors to get pre-trained models.

[paper link](https://eccv2018.org/openaccess/content_ECCV_2018/papers/Yulun_Zhang_Image_Super-Resolution_Using_ECCV_2018_paper.pdf)

Otherwise, you can train it on your own with given scripts (please refer to ``template.py``).

Thank you.
