### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by vvhj** [thstkdgus35/EDSR-PyTorch#122]
3 GPUs takes more time than one GPU

**Comment by thstkdgus35** [comment]
It can happen because distributing data to multiple GPUs may have some overhead.

I recommend running your program with below configurations:

--batch_size 48 --test every 334 --print_every 34 --lr 3e-4

This idea is from [
Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour](https://arxiv.org/pdf/1706.02677.pdf), and I checked that it gives you a linear speed gain.

**Comment by vvhj** [comment]
thanks it works！
72.3+0.6s ==> 51.7+0.8s
