### ISSUE TITLE
how to ues pretrained model

### ISSUE THREAD

**Issue by jilner** [thstkdgus35/EDSR-PyTorch#125]
how to ues pretrained model  test my picture？
thank you very much

**Comment by thstkdgus35** [comment]
Hello.

You can test your model as follows.

1. Put your images under ``/test`` directory (as ``0853x4.png``).

2. Use [this script](https://github.com/thstkdgus35/EDSR-PyTorch/blob/72f5cc26f3033686c96209bae5e9f3e07c7e379e/src/demo.sh#L32) to get output images!

Of course, you should change ``--pre_train download`` to ``--pre_train [path_where_your_model_located]``.

You can find your results under ``experiment/test`` directory.

Otherwise, you can manually set it with ``--save [name_you_want]``.

Thank you!
