### ISSUE TITLE
[Question] Why dump .png into binary for preprocessing?

### ISSUE THREAD

**Issue by Lyken17** [thstkdgus35/EDSR-PyTorch#126]
Dear Author(s)

Thanks for sharing your codebase. Here I have got a question about pre processing: I see many binary ".pt" files are generated, what is the purpose of this operation?

**Comment by thstkdgus35** [comment]
Since .png files are compressed, it takes huge time for loading them into RAM.

Therefore, we just pre-decode them to prevent this overhead.

If you do not want to generate such that many .pt files, you can use ``--ext img`` to directly read .png files.

However, I cannot guarantee the speed in this case :)

Thank you!

**Comment by Lyken17** [comment]
In this case, [Nvidia-DALI](https://github.com/NVIDIA/DALI) may help on accelerating data-preprocessing. Thanks for your reply!

**Comment by thstkdgus35** [comment]
@Lyken17 It looks quite fancy. Thank you for sharing!

**Comment by Lyken17** [comment]
@thstkdgus35  
One more question, I notice in your provided DIV2k, there are only 10 images for testing. But shouldn't there be 100 images?

'''
DIV2K dataset has the following structure:

1000 2K resolution images divided into: 800 images for training, 100 images for validation, 100 images for testing
'''

**Comment by Lyken17** [comment]
Oh I see the problem... Cuz`'--data_range', type=str, default='1-800/801-810',` limits the validation size to be 10.

**Comment by thstkdgus35** [comment]
@Lyken17 You got it. Otherwise, you have to evaluate all 100 images after each epoch... Which is pretty time-consuming.
