### ISSUE TITLE
dataloader does not work for pytorch == 0.3.0

### ISSUE THREAD

**Issue by YapengTian** [thstkdgus35/EDSR-PyTorch#13]
Thank you very much for sharing the code!

There are two Errors when the pytorch version is 0.3.0: 
AttributeError: 'MSDataLoaderIter' object has no attribute 'timeout'
AttributeError: 'MSDataLoaderIter' object has no attribute 'worker_pids_set'.
Thanks!

**Comment by thstkdgus35** [comment]
Hello.

I think you are using PyTorch 0.4 since there are no 'timeout' and 'worker_pids_set' attribute in the dataloader of PyTorch 0.3.

Unfortunately, there are many things to consider to handle your problem.

Because the current official version is 0.3, I will fix my code after 0.4 is released.

Thank you.

Sanghyun.

**Comment by YapengTian** [comment]
Thank you, Sanghyun! I will run it using Pytorch 0.2.

BTW, does your group paticipate NTIRE 2018 Super-Resolution Challenge? Look forward to read new great work from your group!

Best,
Yapeng

**Comment by thstkdgus35** [comment]
I found that PyTorch 0.3.1 changed their implementation of dataloader file.

Therefore, I fixed my dataloader file, too and it will be uploaded soon.

Because the new implementation is not compatible to the old one, new dataloader will be pushed to a new branch first.

By the way, we are not participating this year NTIRE until now, but researches are in progress.

Thank you!

Sanghyun.

**Comment by YapengTian** [comment]
Thank you very much, Sanghyun!
