### ISSUE TITLE
About video test

### ISSUE THREAD

**Issue by beenull** [thstkdgus35/EDSR-PyTorch#145]
when i run video test
there is no result output for long time,maybe 30minutes.
looks like below：

Evaluation:
  0%|                                                   | 0/303 [00:00<?, ?it/s]

is that right？
the test video  11s

**Comment by thstkdgus35** [comment]
Hello.

Since our code process the video frame by frame, there is no limit to video length.

I tested the code with a 1-hour video which had more than 90k frames, but I am not sure about this problem.

Maybe you can check if your video can be parsed into independent frames without problems first.

You can try [this line](https://github.com/thstkdgus35/EDSR-PyTorch/blob/3d1d9b037458d3f94f98f33321fc5e216beed4d0/src/videotester.py#L44) repeatedly.

Otherwise, there can be some problems with video metadata, since our code estimates the total number of frames first and then iterates over those frames.

Check [this line](https://github.com/thstkdgus35/EDSR-PyTorch/blob/3d1d9b037458d3f94f98f33321fc5e216beed4d0/src/videotester.py#L31) to figure out further problems.

Thank you!

**Comment by beenull** [comment]
thank you for your response very much!
I just solved that problem by change 'video' to ['video']  in main.py
it seems  a bug.
