### ISSUE TITLE
SSIM and PSNR

### ISSUE THREAD

**Issue by Auth0rM0rgan** [thstkdgus35/EDSR-PyTorch#147]
Hey @thstkdgus35,

Thanks for sharing your code. How did you calculate SSIM? I couldn't find any function in your source code to calculate it. 
In the calc_psnr function line 176, What is 6 that you sum up it with scale ( `shave = scale + 6`)?

**Comment by thstkdgus35** [comment]
Hello.

We use MATLAB to calculate PSNR and SSIM (the evaluation script is not included in our repository).

Also, it is a convention to crop some boundary pixels from result images before calculating PSNR and SSIM since there can exist boundary artifacts.

Some previous works crop those boundary pixels depend on the super-resolution scale factor, so we did it too.

Thank you!
