### ISSUE TITLE
Loaded model activations

### ISSUE THREAD

**Issue by mattlamont29** [thstkdgus35/EDSR-PyTorch#149]
How can I see the activation functions used in the trained model?
i.e. If I load the model using:
`model = torch.load('../models/edsr_baseline_x4-6b446fab.pt', map_location='cpu')`
then I can see the numerical values of the tensors, but cannot see the activations used (despite them apparently being accessible when the model is actually applied to a new image).

**Comment by thstkdgus35** [comment]
Hello.

Note that the ``.pt`` file does not contain any information of model structure.

It only contains a set of weights and their names.

Since the most common ReLU activation function is not a parametric function, you cannot see any trace of the ReLU in ``.pt`` file.

Please refer to the model script (like [here](https://github.com/thstkdgus35/EDSR-PyTorch/blob/3d1d9b037458d3f94f98f33321fc5e216beed4d0/src/model/edsr.py#L25)) to see which activation is used.

Thank you!

**Comment by mattlamont29** [comment]
Great, thanks very much!
