### ISSUE TITLE
PyTorch training slower than Torch? 

### ISSUE THREAD

**Issue by muneebaadil** [thstkdgus35/EDSR-PyTorch#15]
Hi, I have noticed that Pytorch models are significantly slower than Torch models. Did you experience this too or is it just me?

I am training exactly the same model with same dataset (having same binary format), yet Torch version is significantly faster.

**Comment by thstkdgus35** [comment]
Hello.

Have you checked the patch size of Torch7 and PyTorch version?

The default patch size of PyTorch (output 192x192) is larger than the Torch7 (output 96x96) version.

It is because we found that larger patch size slightly increase the final model performance.

If this was the issue, you can change the patch size for faster training.

Otherwise, please notice me.

Thank you!

Sanghyun.

**Comment by muneebaadil** [comment]
Yes, patch size was the factor for slower speed. It's almost same as Lua version now, thanks. Closing the issue.
