### ISSUE TITLE
Change input channel

### ISSUE THREAD

**Issue by BeepBump** [thstkdgus35/EDSR-PyTorch#153]
Hi, Sorry for bothering!
If I conduct some transform to the input data, how can I change the number of input channel from 3 to 12?
And I need to conduct inverse transform, so the 12-channel output can turn back to 3-channel, where can I modify the code?
Pls~Thanks!

**Comment by thstkdgus35** [comment]
Hello.

You should change the model architecture. I recommend you to create another file for your new model and do experiments with a new model file. Specifically,

1. Copy ``src/model/edsr.py`` to ``src/model/mymodel.py``.

2. Modify [these](https://github.com/thstkdgus35/EDSR-PyTorch/blob/3d1d9b037458d3f94f98f33321fc5e216beed4d0/src/model/edsr.py#L31) [two](https://github.com/thstkdgus35/EDSR-PyTorch/blob/3d1d9b037458d3f94f98f33321fc5e216beed4d0/src/model/edsr.py#L44) lines. Also, class name should be replaced to ``MyModel`` instead of ``EDSR``.

3. Use ``--model mymodel`` argument to use your new model.

Thank you!
