### ISSUE TITLE
A wonder about the option '--reset'.

### ISSUE THREAD

**Issue by m732367606** [thstkdgus35/EDSR-PyTorch#161]
What is the '--reset' option used for? What does the explanation 'reset the training' mean? Is there any theoretical literature who can point out?
Hope somebody can help plz.

**Comment by thstkdgus35** [comment]
Hello.

``--reset`` argument deletes a previous experiment with the same name.

Since our code does not overwrite, but appends the log file if it already exists, ``--reset`` can be convenient if you want to restart the training.

However, sometimes the argument can be dangerous and I recommend not to use that argument when you are doing your own experiment.

Thank you.

**Comment by m732367606** [comment]
Thanks a lot!
