### ISSUE TITLE
About VideoSR

### ISSUE THREAD

**Issue by sxd0071** [thstkdgus35/EDSR-PyTorch#172]
Hi, sorry to bother you. How to use EDSR to train video. Can you offer some advice.Thanks.

**Comment by thstkdgus35** [comment]
Hello.

Sorry for the late response.

Since EDSR is not designed for video inputs, there is no specific way to train the model with video dataset (while considering temporal information).

However, you can still train the model with each frame from the video.

For example, split your video into separate frames and use those images for the training.

Thank you!
