### ISSUE TITLE
Question about using a patch

### ISSUE THREAD

**Issue by chaos5958** [thstkdgus35/EDSR-PyTorch#2]
Hi, I'm a MS student from KAIST.

I have a simple question about patches you are using.
In the code, dataloader gets one random patch per image.
`common.getPatch(...)`

1.I have been implemented super resolution code for iterating all patches in one epoch, but randomly choosing scheme seems a lot easier to implement.
However, randomly 'one' patch per 'one' image seems to require more epoch than above approach (iterating over all patches) for achieving same performance, is it right?
Since default epoch in option.py  is only 60, I'm really curious of it.
2. Also, does randomly choosing approach has equal performance to iterating all patches? 
3. I have been a tensorflow user, so I'm just beginner in pytorch, could I run your code in pytorch 0.3 which is current norm version? Are there any API changes I should take care of?

Thanks for nice code.
Hyunho Yeo.

**Comment by thstkdgus35** [comment]
Hello.

1. As you mentioned, it is more natural to iterate over all patches in one epoch.
However, I guess that there is no significant difference when we iterate over all patches.
Also, I want to notice that the term epoch is not exactly same with other codes.
Although I know what the word epoch means, one epoch in my code iterates over 20 * 800 images for some reason.
(One reason is that we need more epochs when we randomly choose patches, as you mentioned.
Also, many papers on super-resolution report their configurations using the term 'iterations', or 'updates', not epochs.
In my code, one epoch is actually 20 epochs, and contains 1000 iterations(batches).)
Sorry for the confusion.

2. Actually, we did not test it. Maybe you can test it by modifying data class.

3. I think there is no problem, but I will upload a new version of EDSR-PyTorch based on PyTorch 0.3.
If you are not in hurry, please wait for some days. (Maybe in one or two days)

Thank you, and Happy new year!

Sanghyun.

**Comment by chaos5958** [comment]
Thank you for detail and clear answers.
Great!! I'm looking forward to see a new version. 

Thank you,
Hyunho Yeo.

**Comment by chaos5958** [comment]
@thstkdgus35 

I have one more question about epoch, since I will train on my own dataset not on DILVIK.
You comment that one epoch is actually 20 epoch, however I'm a little bit confused when I saw the code. 
"len(self.testLog) +1" seems to determine a real epoch in the program.

1. Could you explain a little about why 1 epoch is 20 epoch in the program?
2. Is is also valid on other dataset not DILVIK?

**Comment by thstkdgus35** [comment]
+ Comments for additional questions (I checked them on my e-mail, but I cannot find the location they are)
-------------------------------------------------------------------------------------------------
In my code, I inherit data.Dataset class to implement DIV2K class in code/data/DIV2K.py.
data.Dataset is a base class for common PyTorch dataset, and we can use 'dataloader' on this class.
(Actually, I re-defined dataloader class at code/dataloader.py for some reason, but many lines are from PyTorch source code.)
Because dataloader supports one-line mutlthreading, it is very useful.

In Dataset class, method __len__ determines the number of samples in the dataset.
It returns `self.args.nTrain * self.repeat.` (Check line 91-93)
[https://github.com/thstkdgus35/EDSR-PyTorch/blob/62678d0fe335efb23cb6f0c003906331ff552618/code/data/DIV2K.py#L91-L93](url)
`self.args.nTrain` is 800, and I defined `self.repeat` to 20 at line 26.
[https://github.com/thstkdgus35/EDSR-PyTorch/blob/62678d0fe335efb23cb6f0c003906331ff552618/code/data/DIV2K.py#L26](url).

Considering that traditional meaning of one epoch is equal to 800 images, my one epoch is actually 20 epochs.
If you hard-code this value, you can freely control the number of iterations in each epoch.
Also, using custom dataset with existing code is possible, but you have to match the file name and format.
I think it is better to implement the custom dataset loader.
Other parts of my code are work well with other dataset.
Thank you.

Sanghyun.
