### ISSUE TITLE
MDSR training

### ISSUE THREAD

**Issue by suke27** [thstkdgus35/EDSR-PyTorch#211]
Hello, i have a question about multi scale training, training x2 x3 x4 in different batch may cause different loss, sometimes the epoch result is best for x2 case but not best for x3 or x4. so could you share how to get a balance or a good strategy for all scale cases during training.

**Comment by thstkdgus35** [comment]
Hello.As you can say, x2 super-resolution result can be the best while x3 and x4 aren't.However, we found that x3 and x4 also achieve competitive performances at that time, even they are not the best.After enough number of iterations, you can get a stabilized model that can perform x2, 3, and 4 super-resolution well together.Thank you!Best, SanghyunSanghyun SonPh.D. CandidateDepartment of ECE, SNU, Seoul, Koreahttps://cv.snu.ac.kr--------- 원본 메일 ---------보낸사람 : suke27 <notifications@github.com>받는사람 : thstkdgus35/EDSR-PyTorch <EDSR-PyTorch@noreply.github.com>참조 : Subscribed <subscribed@noreply.github.com>받은날짜 : 2019-08-09 (금) 16:44:49제목 : [thstkdgus35/EDSR-PyTorch] MDSR training (#211)Hello, i have a question about multi scale training, training x2 x3 x4 in different batch may cause different loss, sometimes the epoch result is best for x2 case but not best for x3 or x4. so could you share how to get a balance or a good strategy for all scale cases during training.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thstkdgus35/EDSR-PyTorch/issues/211?email_source=notifications\u0026email_token=AFHPMXMSRPKMZAII4UGDCP3QDUN65A5CNFSM4IKRNZ7KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HEKTP2A",
"url": "https://github.com/thstkdgus35/EDSR-PyTorch/issues/211?email_source=notifications\u0026email_token=AFHPMXMSRPKMZAII4UGDCP3QDUN65A5CNFSM4IKRNZ7KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HEKTP2A",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
