### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by suke27** [thstkdgus35/EDSR-PyTorch#6]
Hi, I found current program will cost too much memory when test images.
do you try cudnn.benchmark = True
it seems for test 1920x1080 Top memory will reach limit of GPU(my GPU memory is 11G)

**Comment by thstkdgus35** [comment]
Hello.

Thank you for reporting the memory problem.
As I mentioned in the previous issue, I will finish implementing memory-efficient forward function in this weekend.

Thank you.

Sanghyun.

**Comment by suke27** [comment]
Ok, ^ ^
I found you have do update for trainer.py, is it for efficient forward or better psnr result?

**Comment by thstkdgus35** [comment]
Hello.

I found that PyTorch sometimes does not release memory even a specific tensor or variable is obsolete.

However, that memory will be freed naturally when your program requires more memory.

Also, I implemented a memory-efficient forward function in the recent commit.

Please check it out, and I hope it helps to solve your problem.

Thank you.

Sanghyun.

**Comment by suke27** [comment]
Hi, I found you split one image to chips, I found think of it. one problem is do you check the smooth when your merge them to one image. and for process time, it may longer than process as one image.

**Comment by thstkdgus35** [comment]
Actually, those problems are already handled.

When I crop an input image into small patches, I gave them a little margin. (You can check 'shave' in the code.)

For example, when the input image is 1000 x 1000, I crop four 510 x 510 images.

After super-resolution, those parts are just ignored.

Also, I checked that the performance is not decrease when chop_forward is used, and runtime is not increase that much because margins are small.

Thank you.

**Comment by suke27** [comment]
ok, I see. thank you for your reply!
